name: Terraform workflow file

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  Initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out files
        uses: actions/checkout@v4

      - name: Installing terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Initializing terraform and planning
        run: |
          cd terraform/ && terraform init
          terraform validate
          terraform plan
      
